### ISSUE TITLE
win10 报错

### ISSUE THREAD

**Issue by cy920820** [mrzhangfelix/m3u8Downloader#4]
PS C:\Users\admin\Downloads\m3u8\m3u8Down> python .\downloader_lite2.py
开始下载第1个视频,url:https://qvv21d.cdnlab.live/hls/DQrN6XI3oUK1fNnU8CMDdQ/1590168702/7000/7438/7438.m3u8
403
Traceback (most recent call last):
  File ".\downloader_lite2.py", line 236, in <module>
    main()
  File ".\downloader_lite2.py", line 232, in main
    start(real_url,dir,videoName)
  File ".\downloader_lite2.py", line 105, in start
    r = session.get(m3u8_url, timeout=10)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 449, in prepare_request
    p.prepare(
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\models.py", line 388, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'None': No schema supplied. Perhaps you meant http://None?

**Comment by mrzhangfelix** [comment]
你这个是因为下载没有权限的视频吧

**Comment by cy920820** [comment]
> 你这个是因为下载没有权限的视频吧

这个是他们后端做了过期处理，一个 m3u8 链接是有过期时间的，但是我当时跑脚本的时候是在有效期的，我用了 nodejs 去做下载就没问题。。。
